### ISSUE TITLE
Request to add ability to win + disable kill/popup handling

### ISSUE THREAD

**Issue by TaintedEnergy** [mexikoedi/ttt2_role_med#5]
I'd like a convar to enable the medic to win with the last team standing (if they are still alive). 

It would give the medic some concrete reward/purpose to staying alive, rather than simply existing for the sake of existing with no real purpose or gains. Right now, the only way a medic could end up winning is if they kill someone and become an innocent. 

Adding this convar would also create an interesting dynamic where you could threaten the medic and say that they should heal you or they die (and lose).

**Comment by mexikoedi** [comment]
I'm posting the ideas of everyone here. 
I can see them better here and maybe someone has an opinion about this: 

Zzzaaaccc13: "Instead of the medic winning. They should just earn points based on healing/revive. Otherwise there's an incentive for the medic to "join" a team."

TTTPaul (Suggestion for the idea above.): "Or make it so they only win as long as they have also given benefits to the losing team, so if T wins and the medic has only revived/healed traitors then the medic loses. But if the medic has revived/healed both sides above a cutoff then they win regardless of team"

Sven | ZenBreaker: "Or the medic wins, when he gets killed or when he healed a certain amount. Than everyone would be running away from the medic."

Epic Sans (Suggestion for the idea above.): "i find that funny but instead of how long he healed maybe do something where he has to like heal 300 hp to win or something. and if he dies that he instantly wins. if its gonna be added maybe make then a convar for it cause everyone wouldnt like that im pretty sure. some people will tho"

Tim | Mineotopia (Suggestion for the idea above.): "More like a fixed multiplicator as a convar that is multiplied with the amount of players."

**Comment by mexikoedi** [comment]
This was added with the PR #6 .
